# Generated by Django 5.2.7 on 2025-10-22 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_user', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_creator', to='authentication_user.userprofile')),
                ('member', models.ManyToManyField(blank=True, null=True, related_name='forum_member', to='authentication_user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.forum')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.forum')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comment_user', to='authentication_user.userprofile')),
                ('forum_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.forum_post')),
            ],
        ),
    ]
