# Generated by Django 5.2.7 on 2025-10-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_user', to='authentication_user.userprofile'),
        ),
    ]
