# Generated by Django 5.2.7 on 2025-10-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0001_initial'),
        ('community', '0002_alter_forum_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='forum_member', to='authentication_user.userprofile'),
        ),
    ]
