# Generated by Django 5.2.7 on 2025-10-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_forum_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum_Comment',
        ),
    ]
