# Generated by Django 5.2.7 on 2025-10-22 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_lapangan', '0001_initial'),
        ('authentication_user', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_book', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jadwal', models.ManyToManyField(to='admin_lapangan.jadwallapangan')),
                ('lapangan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_lapangan.lapangan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_user.userprofile')),
            ],
        ),
    ]
