# Generated by Django 5.2.7 on 2025-11-21 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_lapangan', '0003_alter_lapangan_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LapanganFavorit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('Rumah', 'Dekat Rumah'), ('Kantor', 'Dekat Kantor'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_lapangan.lapangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lapangan')},
            },
        ),
    ]
