# Generated by Django 5.2.7 on 2025-10-24 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_user', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_lapangan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lapangan_managed', to='authentication_user.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JadwalLapangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('start_main', models.TimeField()),
                ('end_main', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='admin_lapangan.lapangan')),
            ],
            options={
                'ordering': ['tanggal', 'start_main'],
                'unique_together': {('lapangan', 'tanggal', 'start_main')},
            },
        ),
    ]
