# Generated by Django 5.2.6 on 2025-10-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_lapangan', '0001_initial'),
        ('authentication_user', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapangan',
            name='admin',
        ),
        migrations.AddField(
            model_name='lapangan',
            name='admin_lapangan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lapangan_managed', to='authentication_user.userprofile'),
        ),
    ]
