# Generated by Django 5.2.7 on 2025-10-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_lapangan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lapangan',
            old_name='admin',
            new_name='admin_lapangan',
        ),
    ]
