# Generated by Django 5.2.6 on 2025-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_lapangan', '0002_remove_lapangan_admin_lapangan_admin_lapangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapangan',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
